name = "79fb454af39e29373cce48ec72786ffd68453fa8"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2025-05-05"
compatibility_flags = ["nodejs_compat"]

[vars]
NODE_VERSION = "22.15.1"
